"""Update Posts and Comments schema

Revision ID: 1bf515dcb623
Revises: 7e64c63476af
Create Date: 2017-11-02 18:54:15.745929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf515dcb623'
down_revision = '7e64c63476af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posts_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['posts_id'], ['id'])
    op.drop_constraint('posts_comment_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_comment_id_fkey', 'posts', 'comments', ['comment_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'posts_id')
    # ### end Alembic commands ###
