"""Update Migration for Bliss_Posts

Revision ID: cc351ca155e7
Revises: 5d424df13602
Create Date: 2017-11-01 01:36:04.791888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc351ca155e7'
down_revision = '5d424df13602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_pic')
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('post_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
