"""Update Posts and Comments schema fk

Revision ID: ed16d7f6a066
Revises: 1bf515dcb623
Create Date: 2017-11-02 19:22:35.480100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed16d7f6a066'
down_revision = '1bf515dcb623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_posts_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['posts_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_posts_id_fkey', 'comments', 'comments', ['posts_id'], ['id'])
    # ### end Alembic commands ###
